INSERT INTO public.product VALUES (DEFAULT, 'CAFÉ', FALSE, 600);
INSERT INTO public.product VALUES (DEFAULT, 'XICARA', FALSE, 200);
INSERT INTO public.product VALUES (DEFAULT, 'COLHER', FALSE, 50);
INSERT INTO public.product VALUES (DEFAULT, 'LAVAGEM VEICULAR', TRUE, 100);
INSERT INTO public.product VALUES (DEFAULT, 'LIMPEZA DE RESIDENCIA', TRUE, 500);

INSERT INTO public.solicitation VALUES (DEFAULT, 'PEDIDO A', 0, 0);
INSERT INTO public.solicitation VALUES (DEFAULT, 'PEDIDO B', 0, 0);
INSERT INTO public.solicitation VALUES (DEFAULT, 'PEDIDO C', 1, 0);




